let dataArr = [
  {
    playerName: "Rohit Sharma",
    from: "MI",
    price: "6.50 Cr",
    isPlaying: true,
    championshipsWon: 3,
    description: "Batsman",
    logo: "https://www.pngall.com/wp-content/uploads/2017/04/Mumbai-Indians-Logo-PNG.png",
    photo: "https://static.iplt20.com/players/284/107.png",
  },

  {
    playerName: "MS Dhoni",
    from: "CSK",
    price: "6.50 Cr",
    isPlaying: true,
    championshipsWon: 3,
    description: "Wicketkeeper batsman",
    logo: "https://www.pngall.com/wp-content/uploads/2017/04/Chennai-Super-Kings-Logo-PNG.png",
    photo: "https://static.iplt20.com/players/284/1.png",
  },

  {
    playerName: "Virat Kohli",
    from: "RCB",
    price: "6.50 Cr",
    isPlaying: false,
    championshipsWon: 3,
    description: "Batsman",
    logo: "https://cdn.statically.io/img/kreditings.com/wp-content/uploads/2020/09/RCB-png-logo-2020.png?quality=100&f=auto",
    photo: "https://static.iplt20.com/players/284/164.png",
  },
  {
    playerName: "Sanju Samson",
    from: "RR",
    price: "6.50 Cr",
    isPlaying: true,
    championshipsWon: 3,
    description: "Wicketkeeper batsman",
    logo: "https://cdn.statically.io/img/kreditings.com/wp-content/uploads/2020/09/RR-Logo.png?quality=100&f=auto",
    photo: "https://static.iplt20.com/players/284/258.png",
  },

  {
    playerName: "Rishabh Pant",
    from: "DC",
    price: "6.50 Cr",
    isPlaying: true,
    championshipsWon: 3,
    description: "Wicketkeeper-batsman",
    logo: "https://cdn.statically.io/img/kreditings.com/wp-content/uploads/2020/09/Delhi-Capital-_Logo.png?quality=100&f=auto",
    photo: "https://static.iplt20.com/players/284/2972.png",
  },
  {
    playerName: "Hardik Pandya",
    from: "MI",
    price: "6.50 Cr",
    isPlaying: true,
    championshipsWon: 3,
    description: "All-rounder",
    logo: "https://www.pngall.com/wp-content/uploads/2017/04/Mumbai-Indians-Logo-PNG.png",
    photo: "https://static.iplt20.com/players/284/2740.png",
  },
  {
    playerName: "Dwanye Bravo",
    from: "CSK",
    price: "6.50 Cr",
    isPlaying: false,
    championshipsWon: 3,
    description: "All-rounder",
    logo: "https://www.pngall.com/wp-content/uploads/2017/04/Chennai-Super-Kings-Logo-PNG.png",
    photo: "https://static.iplt20.com/players/284/25.png",
  },
  {
    playerName: "Ajinkya Rahane",
    from: "DC",
    price: "6.50 Cr",
    isPlaying: false,
    championshipsWon: 3,
    description: "Batsman",
    logo: "https://cdn.statically.io/img/kreditings.com/wp-content/uploads/2020/09/Delhi-Capital-_Logo.png?quality=100&f=auto",
    photo: "https://static.iplt20.com/players/284/135.png",
  },
];

module.exports = dataArr;
